version: "3"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    restart: always
  # pspiechart:
  #   volumes: 
  #     - /tmp/pspiechart/:/tmp/
  #   build:
  #     context: pspiechart
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080"]
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s
  # sensornet-server:
  #   build:
  #     context: sensornet-server
  #     dockerfile: Dockerfile
  #   environment:
  #     - INFLUXDB_TOKEN=V6LpG_9ksP30dJ009jbRcCwUhLakamnE7rrjnLGFxpVlWb4yc8k_GpB8dPVELDxycDr0QwvNUGsCnX3mbTJu3A==
  #   ports:
  #     - 8080:8080
  #     - 5001:5001/udp