version: "3"

services:
  influxdb:
    image: influxdb:latest
    # ports:
    #   - 8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=super-secret-influx-pwd
      - DOCKER_INFLUXDB_INIT_ORG=psp-liquids
      - DOCKER_INFLUXDB_INIT_BUCKET=sensornet
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super-secret-influx-token
    restart: always

  pocketbase:
    build: ./pocketbase
    ports:
      - 8093:8093
    volumes:
      - ./data/pocketbase:/pb/pb_data
      - ./pocketbase/migrations:/pb/pb_migrations
    environment:
      - VIRTUAL_HOST=pb.*
      - VIRTUAL_PORT=8093

  pspiechart:
    build: ./pspiechart
    ports:
      - 4173:4173
    environment:
      - VIRTUAL_HOST=pspc.*
      - VIRTUAL_PORT=4173
    restart: always

  sensornet-server:
    build: ./sensornet-server
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_ORG=psp-liquids
      - INFLUXDB_BUCKET=sensornet
      - INFLUXDB_TOKEN=super-secret-influx-token
      - DB_PATH=/data

      - VIRTUAL_HOST=sensornet.*
      - VIRTUAL_PORT=8080
    volumes:
      - ./data/sensornet-server:/data
    ports:
      - 8080:8080
      - 5001:5001/udp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
