FROM node:latest

RUN wget https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.3-linux-amd64.tar.gz
RUN tar xvzf influxdb2-client-2.7.3-linux-amd64.tar.gz
RUN cp influx /usr/local/bin/

WORKDIR /app

EXPOSE 8080
EXPOSE 5001/udp

CMD ["yarn", "dev"]